apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-react
  labels:
    app: simple-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-react
  template:
    metadata:
      labels:
        app: simple-react
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: simple-react
        image: konami98/simple-react:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80