apiVersion: v1
kind: Service
metadata:
  name: simple-react
  labels:
    app: simple-react
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 30000  # Changed from NodePort to nodePort
  selector:
    app: simple-react