name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: konami98/simple-react

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker System Cleanup
        run: |
          docker system prune -af --volumes || true
          docker images ${{ env.DOCKER_IMAGE }} -q | xargs -r docker rmi || true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Docker Build & Push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          IMAGE_TAG=${{ github.run_number }}
          FULL_IMAGE_NAME=${{ env.DOCKER_IMAGE }}:$IMAGE_TAG
          LATEST_IMAGE_NAME=${{ env.DOCKER_IMAGE }}:latest
          docker build --no-cache -t $FULL_IMAGE_NAME -t $LATEST_IMAGE_NAME ./frontend
          docker push $FULL_IMAGE_NAME
          docker push $LATEST_IMAGE_NAME